api_root_path: /
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_connection_str: '**********'
db_name: dev_db
docs_url: /docs
host: 127.0.0.1
kafka_servers:
- kafka:9092
log_level: info
openapi_url: /openapi.json
port: 8080
sample_updated_event_topic: sample_events
sample_updated_event_type: sample_updated
service_instance_id: '1'
service_name: cm
update_sample_event_topic: sample_events
update_sample_event_type: update_sample
workers: 1
