components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    PcrTest:
      description: Simple DTO for the PCR tests
      properties:
        access_token:
          default: ''
          title: Access Token
          type: string
        collection_date:
          title: Collection Date
          type: string
        patient_pseudonym:
          title: Patient Pseudonym
          type: string
        sample_id:
          default: ''
          title: Sample Id
          type: string
        status:
          default: ''
          title: Status
          type: string
        submitter_email:
          title: Submitter Email
          type: string
        test_date:
          default: ''
          title: Test Date
          type: string
        test_result:
          default: ''
          title: Test Result
          type: string
      required:
      - patient_pseudonym
      - submitter_email
      - collection_date
      title: PcrTest
      type: object
    UpdatePcrTest:
      description: Update DTO for PcrTest
      properties:
        access_token:
          title: Access Token
          type: string
        status:
          default: ''
          title: Status
          type: string
        test_date:
          default: ''
          title: Test Date
          type: string
        test_result:
          default: ''
          title: Test Result
          type: string
      required:
      - access_token
      title: UpdatePcrTest
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /:
    get:
      description: Greet the World
      operationId: index__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Greet the world
  /sample:
    patch:
      description: "Update a test sample with results.\nHandle PATCH req:\n    1.\
        \ Find sample with matching access_token\n    2. Update sample\n    3. Return\
        \ updated sample"
      operationId: update_sample_sample_patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePcrTest'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Sample
    post:
      description: "Upload a new sample.\nHandle POST req:\n    1. Insert new data\n\
        \    2. Return sample_id and access_token"
      operationId: post_sample_sample_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PcrTest'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Post Sample
  /sample/{access_token}:
    get:
      description: "Search for a test sample matching the access token.\nHandle GET\
        \ req:\n    1. Return test sample information if found"
      operationId: get_sample_sample__access_token__get
      parameters:
      - in: path
        name: access_token
        required: true
        schema:
          title: Access Token
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Sample
